# Generated by Django 4.1.4 on 2023-02-11 14:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='price')),
                ('date_during', models.CharField(max_length=256, verbose_name='date_during')),
            ],
            options={
                'verbose_name': 'premium',
                'verbose_name_plural': 'Premiums',
            },
        ),
        migrations.CreateModel(
            name='PremiumOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(auto_now_add=True, verbose_name='from_date')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premium_owner', to=settings.AUTH_USER_MODEL, verbose_name='premium_owner')),
                ('premium', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='premium_order', to='premium.premium', verbose_name='premium_order')),
            ],
            options={
                'verbose_name': 'premium order',
                'verbose_name_plural': 'Premium orders',
            },
        ),
    ]
