# Generated by Django 4.1.4 on 2023-02-03 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('image', models.ImageField(upload_to='chat images/', verbose_name='chat_images')),
                ('members', models.ManyToManyField(related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='chat_owner', to=settings.AUTH_USER_MODEL, verbose_name='chat_owner')),
            ],
            options={
                'verbose_name': 'chat',
                'verbose_name_plural': 'Chats',
            },
        ),
    ]
