# Generated by Django 4.1.4 on 2023-02-08 08:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_active',
            field=models.BooleanField(default=False, verbose_name='premium_active'),
        ),
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.IntegerField(default=0, verbose_name='wallet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 8, 25, 49, 753482, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
