# Generated by Django 4.1.4 on 2023-02-08 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_premium_active_user_wallet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 8, 8, 50, 26, 864681, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
