# Generated by Django 4.1.4 on 2023-01-30 09:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_last_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'Skills',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 30, 9, 54, 41, 851114, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('from_date', models.DateTimeField(auto_now=True, verbose_name='from_date')),
                ('to_date', models.DateTimeField(auto_now=True, verbose_name='to_date')),
                ('description', models.TextField(verbose_name='description')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_experience_owner', to=settings.AUTH_USER_MODEL, verbose_name='work_experience_owner')),
            ],
            options={
                'verbose_name': 'work experience',
                'verbose_name_plural': 'Works experiences',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('from_date', models.DateTimeField(auto_now=True, verbose_name='from_date')),
                ('to_date', models.DateTimeField(auto_now=True, verbose_name='to_date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_owner', to=settings.AUTH_USER_MODEL, verbose_name='education_owner')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'Educations',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='skill',
            field=models.ManyToManyField(to='users.skills', verbose_name='skill'),
        ),
    ]
