# Generated by Django 4.1.4 on 2023-02-01 18:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_skills_alter_user_last_activity_workexperience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='workexperience',
            name='owner',
        ),
        migrations.AddField(
            model_name='user',
            name='education',
            field=models.ManyToManyField(to='users.education', verbose_name='education'),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.ManyToManyField(to='users.workexperience', verbose_name='work_experience'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 19, 25, 964091, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
