# Generated by Django 4.1.4 on 2023-02-01 18:38

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_education_owner_remove_workexperience_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='education',
        ),
        migrations.RemoveField(
            model_name='user',
            name='work_experience',
        ),
        migrations.AddField(
            model_name='education',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='education_owner', to=settings.AUTH_USER_MODEL, verbose_name='education_owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workexperience',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_experience_owner', to=settings.AUTH_USER_MODEL, verbose_name='work_experience_owner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 18, 38, 46, 893016, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
    ]
