# Generated by Django 4.1.4 on 2023-02-01 19:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_user_education_remove_user_work_experience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='education',
            name='from_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='from_date'),
        ),
        migrations.AlterField(
            model_name='education',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='education', to=settings.AUTH_USER_MODEL, verbose_name='education'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='education',
            name='to_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='to_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_activity',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 1, 19, 4, 14, 938825, tzinfo=datetime.timezone.utc), verbose_name='last_activity'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='from_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='from_date'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_experience', to=settings.AUTH_USER_MODEL, verbose_name='work_experience'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='title',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='to_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='to_date'),
        ),
    ]
